[[main]]
  name = "Documentazione"
  url = "/docs/piattaforma/cloud/"
# url = "/docs/1.0/prologue/cloud/"
  weight = 10


[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "ESP32"
  url = "/tags/esp32/"
  weight = 25

[[main]]
  name = "Come iniziare"
  weight = 30
  identifier = "get-started"
  url = "/docs/piattaforma/cloud/"

[[main]]
  name = "Quick Start"
  weight = 40
  identifier = "quick-start"
  url = "/docs/piattaforma/quick-start/"
  parent = "get-started"

[[main]]
  name = "Argomenti"
  weight = 60
  identifier = "tags"
  url = "/argomenti"
  parent = "get-started"

[[main]]
  name = "Ecommerce"
  weight = 70
  identifier = "ecommerce"
  url = "https://robotdazero.company.site/"
  parent = "get-started"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://gist.github.com/sebadima"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"> <path d=\"M4 4l11.733 16H20L8.267 4z\"></path><path d=\"M4 20l6.768-6.768m2.46-2.46L20 4\"></path></svg>"
  url = "https://twitter.com/robofromscratch"
  weight = 20

# https://www.svgrepo.com/svg/433159/sign-in-alt
[[social]]
  name = "Kaspian"
  pre = "<svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"   d=\"m13 16 4-4-4-4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"   d=\"M17 12H3M13.6 3h5A2.4 2.4 0 0 1 21 5.4v13.2a2.4 2.4 0 0 1-2.4 2.4H13\" stroke=\"currentColor\" stroke-width=\"2\" stroke-miterlimit=\"10\" stroke-linecap=\"round\"/></svg>"
  url = "https://dash.robotdazero.it/admin/"
  weight = 30


[[footer]]
  name = "Privacy"
  url = "/privacy/"
  weight = 10

[[footer]]
  name = "Contatti"
  url = "/contatti/"
  weight = 10
